model = "gpt-5.1-codex-max"
model_reasoning_effort = "medium"

[projects."/Users/henry/coding/clojure-web-apps/streamdown"]
trust_level = "trusted"

[projects."/Users/henry/coding/clojure-web-apps/datalift"]
trust_level = "trusted"

[projects."/Users/henry/coding/clojure-web-apps/datalift".mcp_servers.clojure-mcp]
command = "docker"
args = [
  "exec",
  "-i",
  "clojure-mcp-server",
  "clojure",
  "-X:mcp",
  ":host", "\"main-server\"",
  ":port", "7001"
]

[projects."/Users/henry/coding/clojure-web-apps/datalift".mcp_servers.postgres-mcp]
command = "docker"
args = [
  "run",
  "-i",
  "--rm",
  "-e",
  "DATABASE_URI",
  "crystaldba/postgres-mcp",
  "--access-mode=restricted"
]
env = { "DATABASE_URI" = "postgresql://postgres:postgres@localhost:5556/datalift" }

[mcp_servers.context7]
command = "mcp-proxy"
args = ["--transport", "streamablehttp", "https://mcp.context7.com/mcp"]

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest", "--extension"]
